### ISSUE TITLE
Submission failure

### ISSUE THREAD

**Issue by lizuoyue** [crowdAI/mapping-challenge-starter-kit#3]
Hello, I just make three submissions (5795, 5796 and 5697).

However, the server post the following error:
`Argument 'bb' has incorrect type (expected numpy.ndarray, got list)`.

Actually, JSON does not support "numpy.ndarray" format, right? I don't know why it posts this kind of error as my first try (submission 5731, only contains very few annotations) has no errors. I see the admin @spMohanty also had this kind of error before (submission 4617). Does anyone know what results in this problem and how to solve this?

Thank you very much!

**Comment by spMohanty** [comment]
@lizuoyue : I dont really remember why I got that error.
But for now can you confirm if you can load your annotations using the [cocoapi](https://github.com/cocodataset/cocoapi) ?

If you really cannot debug the issue, do send me your submission file at [sharada.mohanty@epfl.ch](sharada.mohanty@epfl.ch) and I can have a closer look at it over the weekend.

**Comment by lizuoyue** [comment]
Actually, according to the [random submission](https://github.com/crowdAI/crowdai-mapping-challenge-mask-rcnn/blob/master/Prediction-and-Submission.ipynb) page, the result JSON format (list of dict) is different from the training/validation annotation JSON format (just dict), thus the result JSON file cannot be successfully loaded by COCOAPI.

Anyway, I will try to debug today. If it still not works, I will send @spMohanty the submission file. Thank you very much!

Hereby I also post the error information for reference. It stops at 25% when evaluation.
```
Zuoyue-Li:src LIZUOYUE$ python3 Submit.py
CrowdAI.Event.Authentication : Authenticating for challenge = crowdAIMappingChallenge
CrowdAI.Event.Connection.CONNECTED
CrowdAI.Event.Authentication.SUCCESS : Authentication Successful
CrowdAI.Event.Misc.FILE_UPLOAD : Preparing for file upload
CrowdAI.Event.Misc.FILE_UPLOAD : Uploading file
100% |██████████████████████████████████████████████████████████████████████████████|[00:04<00:00]  22.40% /s] 
CrowdAI.Event.Job.ENQUEUED : bd258838-c6ed-4fe0-9074-8f6d4bec55ca                                              
CrowdAI.Event.Job.RUNNING : bd258838-c6ed-4fe0-9074-8f6d4bec55ca                                               
CrowdAI.Event.Job.INFO : (bd258838-c6ed-4fe0-9074-8f6d4bec55ca) Grading Submission....                         
CrowdAI.Event.Job.INFO : (bd258838-c6ed-4fe0-9074-8f6d4bec55ca) Loading Ground Truth Annotations...            
CrowdAI.Event.Job.INFO : (bd258838-c6ed-4fe0-9074-8f6d4bec55ca) Loading Predicted Annotations...               
CrowdAI.Event.Job.INFO : (bd258838-c6ed-4fe0-9074-8f6d4bec55ca) Predicted Annotations Loaded Successfully...   
CrowdAI.Event.Job.INFO : (bd258838-c6ed-4fe0-9074-8f6d4bec55ca) Initiating evaluation. This might take a few minutes. Hang in there :D 
bd258838-c6ed-4fe0-9074-8f6d4bec55ca:  25% |██████▊                    |[00:56<00:46]   1.62% /s] Traceback (most recent call last):
  File "Submit.py", line 4, in <module>
    result = challenge.submit('newpredictions.json')
  File "/usr/local/lib/python3.6/site-packages/crowdai/challenges/crowdai_mapping_challenge.py", line 54, in submit
    [{"file_key": file_key}]
  File "/usr/local/lib/python3.6/site-packages/crowdai/challenges/base_challenge.py", line 178, in execute_function
    self.socketio.wait_for_callbacks(seconds=self.config['challenges'][self.challenge_id]["TIMEOUT_EXECUTION"])
  File "/usr/local/lib/python3.6/site-packages/socketIO_client/__init__.py", line 450, in wait_for_callbacks
    self.wait(seconds, for_callbacks=True)
  File "/usr/local/lib/python3.6/site-packages/socketIO_client/__init__.py", line 245, in wait
    self._process_packets()
  File "/usr/local/lib/python3.6/site-packages/socketIO_client/__init__.py", line 269, in _process_packets
    self._process_packet(engineIO_packet)
  File "/usr/local/lib/python3.6/site-packages/socketIO_client/__init__.py", line 496, in _process_packet
    delegate(packet)
  File "/usr/local/lib/python3.6/site-packages/socketIO_client/__init__.py", line 516, in _on_event
    packet.namespace._find_packet_callback(event)(*args)
  File "/usr/local/lib/python3.6/site-packages/crowdai/challenges/base_challenge.py", line 87, in on_execute_function_response
    raise CrowdAIExecuteFunctionError(payload["message"])
crowdai.challenges.crowdai_errors.CrowdAIExecuteFunctionError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list)
```

**Comment by spMohanty** [comment]
@lizuoyue : Yeah the format is indeed slightly different that the annotations.
But coco API is still consistently used to load the annotations.

Can you follow the instructions [here](https://github.com/crowdAI/mapping-challenge-starter-kit/blob/master/Local%20Evaluation.ipynb) to locally test your submission.

**Comment by lizuoyue** [comment]
@spMohanty: Thanks Mohanty, I finally fix the bug.
The error is caused by the COCO's `annToRLE` function, when feeding segmentation with only 2 points (4 numbers).
